# Generated by Django 3.2.4 on 2021-06-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Author', models.CharField(blank=True, max_length=50, null=True)),
                ('CreatedDate', models.DateField(auto_now=True)),
                ('ReferenceLink', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'BlogPost',
            },
        ),
    ]
